upd.port = 11111

# Java 21+ Virtual Threads (Essential for blocking IO like file downloading)
spring.threads.virtual.enabled=true

# Tomcat optimizations for Large Files
server.tomcat.threads.max=200
server.tomcat.max-swallow-size=20MB

#not compatible with webflux so disable it
spring.servlet.multipart.enabled=true

spring.servlet.multipart.location=${user.dir}/data/tmp

spring.servlet.multipart.file-size-threshold=256MB
spring.servlet.multipart.max-file-size=1TB
spring.servlet.multipart.max-request-size=1TB

# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

#spring.banner.location=classpath:banner.txt

spring.mvc.async.request-timeout=-1

app.storage.limit=26843545600

# Graceful shutdown configurations
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=1m
spring.task.execution.shutdown.await-termination=true
spring.task.execution.shutdown.await-termination-period=1m
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=1m