server:
  port: 9005
#  http2: 
#    enabled: true
#  compression:
#    enabled: true
#    mime-types: text/html,text/plain,text/css,application/javascript,application/json
#    min-response-size: 1024
  
#  servlet:
#    session:
#      timeout: 60m
spring:
  application:
    name: sync
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:h2:file:${user.dir}/data/sync
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
         
logging: 
  file:
    name: ${user.dir}/data/sync.log
  level:
    #    '[com.zaxxer.hikari]': DEBUG
    com: 
      source: 
        open: INFO 
  logback.rollingpolicy.max-history: 5 
  logback.rollingpolicy.max-file-size: 1MB

